export const GET_HEISTS = 'GET_HEISTS';
export const SHOW_EDIT_HEIST_FORM_WINDOW = 'SHOW_EDIT_HEIST_FORM_WINDOW';
export const UPDATE_HEIST = 'UPDATE_HEIST';
export const SET_SELECTED_HEIST = 'SET_SELECTED_HEIST';
